kubernetes-sigs/kubebuilder-declarative-pattern

- hack/ci/test.sh
- pkg/doc.go
- pkg/patterns/addon/pkg/doc.go
- pkg/patterns/doc.go
- Add a CI script for prow presubmits
- Add doc.go files to packages that have no go files so go test will
traverse them.
> add empty test targets

- docs/addon/walkthrough/README.md
There is a merge conflict at section of "Adding the framework into our types" in docs/addon/walkthrough/README.md
This PR fix conflict by following current contents of pkg/apis/addons/v1alpha1/dashboard_types.go
> Fix merge conflict section in walkthrough

- examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
This option makes it easier to remove dropped objects inbetween releases
(eg, foo deployment in v1, foo statefulset in v2)
fixes #4
> declarative: Add WithApplyPrune

- pkg/patterns/addon/init.go
This boilerplate is now included at the top of kubebuilder's generated
main() function. Calling it before the generated code results in
main() declared flags from not being recognized.
> pkg/patterns/addon/init: Drop flag parsing

- doc.go
- docs/addon/walkthrough/README.md
- examples/dashboard-operator/config/default/kustomization.yaml
- examples/dashboard-operator/config/default/manager_resource_patch.yaml
- Remove bazel for direct dockerfile builds.
- Reference actual repo path and don't rely on unimplemented kubebuilder
flag.
- Rely on kubebuilders RBAC generation and give the set of roles needed
for the dashboard operator
- Tighten up some language
updates #3
> docs/addon/walkthrough: Cleanup pass

- examples/dashboard-operator/Makefile
Fake the vendoring of the kubebuilder-declarative-operator library by
copying it into vendor in just the right spot.
This odd move is needed to builder the Docker container. I'd like to
make it look as much like the walkthrough as possible, or else I'd
modify the Dockerfile to live at the root of the project.
> examples/dashboard-operator: fake vendor directory

- examples/dashboard-operator/Makefile
- examples/dashboard-operator/config/default/manager_image_patch.yaml
This is a more reasonable default for those lucky enough that `$USER == $dockerhub login`
> dashboard-operator: default image name to $USER/dashboard-operator

- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
This enables it to be configured or changed.
> Make the default manifest loader pluggable

- pkg/patterns/addon/init.go
- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
This change removes the dependency between the declarative and addon
package. This allows non-addon users to utilize the declarative
reconciler with their own manifest loader.
> declarative,addon: Configure the filesystem loader in addon.Init

- docs/addon/walkthrough/README.md
- examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
- pkg/patterns/declarative/reconciler.go
The addon manifest loader uses the 'ComponentName()' call on
'CommonSpec' to resolve the component to load the manifest from.
We could do this directly in declarative by requiring packageName and
bubbling it out to the Loader, but there's no reason for the declarative
controller to keep track of this value. The library can't make decisions
about which package to use beyond passing a string it was given.
Pushing this out to the addon/loader allows implementers to own the
decision and perhaps change it at runtime based on the CRs configuration
or the state of CLI flags.
fixes #33
> declarative,docs: remove packageName

- examples/dashboard-operator/cmd/manager/main.go
- pkg/patterns/addon/init.go
- pkg/patterns/declarative/image.go
- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
- Add the Options.{Begin,Eng} variable to declarative which enables users
to specify global transforms for the Reconciler.
- Add --{private-registry,image-pull-secret} flags to addon operators and
inject the ImageRegistryTransform when set.
fixes #35
> declarative,addon: global pipeline, basic registry support

- pkg/patterns/declarative/pkg/watch/dynamic.go
A Watch will be dropped by the server periodically. We want to maintain
the watch as long as the operator is running. This change resumes the
Watch then it is closed by the server and maintains the ResourceVersion
to reduce noise.
fixes #7
> declarative/watch: resume watch on failure

- pkg/test/mocks/client.go
- pkg/test/mocks/manager.go
Extend mock support in a couple ways:
> Allow injecting a Client into a mock Manager
> Add key-value response functionality to FakeClient
This allows clients of this repo to write basic tests that add fake objects into the client and retrieve them later.
> Extend Mocks

- docs/addon/walkthrough/README.md
- examples/dashboard-operator/config/crds/addons_v1alpha1_dashboard.yaml
- examples/dashboard-operator/config/rbac/rbac_role.yaml
- examples/dashboard-operator/config/samples/addons_v1alpha1_dashboard.yaml
- examples/dashboard-operator/pkg/apis/addons/v1alpha1/doc.go
- examples/dashboard-operator/pkg/apis/addons/v1alpha1/register.go
- examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
- examples/dashboard-operator/pkg/controller/dashboard/tests/simple.in.yaml
- examples/dashboard-operator/pkg/controller/dashboard/tests/simple.out.yaml
k8s.io is reserved for Kubernetes APIs. We don't want users to assume
this domain can be used by any extension or addon. The API group
should be a valid domain controlled by the author (or one dedicated to
examples such as example.{com,net,org})
> docs/dashboard-operator: switch to example.org

- pkg/patterns/addon/init.go
This means we don't need to put a call to addon.Init into main, which
simplifies code generation.  Instead, we call it before we first call
into the addon framework - which means we can do so in the
controllers.
> Tolerate multiple calls to addon.Init

- pkg/test/golden/validator.go
- pkg/test/mocks/client.go
- pkg/test/mocks/manager.go
Currently, `FakeClient` doesn't implement `Create` method.
Some tests need to set specific resource object.
This PR implements `Create` method in `FakeClient`.
Fixes: #47
Related: kubernetes-sigs/addon-operators#19
> Implement Create method in FakeClient

- pkg/patterns/declarative/watch.go
by appending namespace to the registered key.
> Allow watching objects with the same name but different namespaces

- pkg/patterns/declarative/image.go
- pkg/patterns/declarative/labels.go
This PR adds debug log messages to functions that transform object by `V(1)` logger.
Fixes: #54
> Add debug log to functions transforms object

- examples/dashboard-operator/channels/packages/dashboard/1.10.1/manifest.yaml
This PR adds manifests for dashboard 1.10.1 to channels folder.
Current stable version of dashboard is 1.10.1, but dashboard-operator doesn't have manifests of it.
If you would like to deploy dashboard 1.10.1, edit `channels/stable` file or set the `spec.channel` field to `1.10.1` in Dashboard CR
> Add dashboard 1.10.1 manifests to channels

- go.mod
- pkg/patterns/addon/patch.go
- pkg/patterns/addon/pkg/loaders/fs.go
- pkg/patterns/addon/pkg/loaders/types.go
- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/declarative/labels.go
- pkg/patterns/declarative/pkg/kubectlcmd/client.go
- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/patch.go
- pkg/patterns/declarative/pkg/watch/dynamic.go
- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/sort.go
- pkg/patterns/declarative/watch.go
pkg/runtime/log is now deprecated (and pulls in the zap library, which
shouldn't be required)
> controller-runtime: pkg/runtime/log -> pkg/log

- examples/dashboard-operator/go.mod
- examples/dashboard-operator/go.sum
- go.mod
- go.sum
- pkg/test/mocks/cache.go
- pkg/test/mocks/client.go
We shouldn't be pinnned to a beta version, now that a released version
of 0.2 is available.
> Update go.mod dependency to kubebuilder 0.2.2

- pkg/patterns/declarative/image.go
Another update to follow the controller-runtime package deprecation,
that I missed last time because of concurrent PRs.
> controller-runtime: pkg/runtime/log moved to pkg/log

- pkg/patterns/addon/pkg/status/aggregate.go
This PR adds field names of `types.NamespacedName` instance when initialize.
This PR fixes some `go vet` messages. For detail, please see #70.
Fixes: #70
> Add field names when create types.NamespacedName

- go.mod
- pkg/patterns/addon/init.go
- pkg/patterns/addon/pkg/loaders/fs.go
- pkg/patterns/addon/pkg/loaders/http.go
- pkg/patterns/addon/pkg/loaders/types.go
- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
Initial fetching from an http/https channel
Currently channels must be explicitly specified with an http:// or
https:// URL, no authentication is supported, etc.
> Fetch manifests over http/https

- go.mod
- pkg/patterns/addon/pkg/loaders/types.go
We should use the k8s version of the libraries.
> Replace yaml.v2 with sigs.k8s.io/yaml

- docs/addon/walkthrough/README.md
Fixed the command for generate `manager_resource_patch.yaml` file: `echo` -> `cat`
Also removed all trailing spaces.
> Fix command for generate patch yaml file

- docs/addon/walkthrough/README.md
- examples/dashboard-operator/channels/stable
- go.mod
- go.sum
- pkg/patterns/addon/pkg/loaders/fs.go
- pkg/patterns/addon/pkg/loaders/types.go
- pkg/patterns/addon/pkg/loaders/versions_test.go
- pkg/test/mocks/client.go
We now allow a package name to be specified, but manifests with no
name are assumed to match all packages.  Where there is a tie, we
prefer a named package, and then we prefer the newer version.
(Previous version of this commit was a breaking change ... no longer)
> Support multiple packages in a channel manifest file

- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
This puts any objects that cannot be parsed into Unstructured.unstructured into a blob.
> Makes file loading more flexible

- examples/guestbook-operator/Dockerfile
- examples/guestbook-operator/Makefile
- examples/guestbook-operator/config/manager/kustomization.yaml
- examples/guestbook-operator/go.mod
- examples/guestbook-operator/go.sum
- hack/smoketest.go
In PR #81, dashboard-operator is removed in this repository.
It is needed that change to use guestbook-operator in `hack/smoketest.go` instead of dashboard-operator.
related to: #80
> Use guestbook-operator in smoketest

- go.mod
- pkg/patterns/addon/pkg/loaders/types.go
For consistency, we should use log instead of klog in the semver comparison
logic.
> Use log instead of klog

- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/pkg/kubectlcmd/client.go
- pkg/patterns/declarative/pkg/kubectlcmd/client_test.go
- pkg/patterns/declarative/reconciler.go
It needs to download the whole OpenAPI spec, which is very expensive
in terms of memory (and generally).  As we expect to tightly control
our manifest, it isn't very useful anyway.
Expose an option WithApplyValidation to use the legacy behaviour.
> Don't use kubectl --validate

- pkg/patterns/declarative/pkg/manifest/objects.go
This makes the message more actionable and self-explanatory.
> Log yaml and error when we fail to parse

- pkg/patterns/declarative/reconciler.go
Because we can execute concurrently, we shouldn't reuse the in-memory
filesystem instance; construct a new one for each reconcile.
Also be more rigorous in exiting on errors.
> Avoid reusing filesystem, cleanup some error handling

- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/reconciler.go
- pkg/test/golden/validator.go
Kustomize cannot find the `kustomization.yaml` file for creating the final manifest.
The error before this fix:
```
2020-04-17T13:13:20.045-0400	ERROR	running kustomize to create final manifest	{"error": "unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/'"}
github.com/go-logr/zapr.(*zapLogger).Error
/Users/srajan/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative.(*Reconciler).reconcileExists
/Users/srajan/go/pkg/mod/sigs.k8s.io/kubebuilder-declarative-pattern@v0.0.0-20200415210853-85eb326a6add/pkg/patterns/declarative/reconciler.go:145
sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative.(*Reconciler).Reconcile …
```
> Fix incorrect path for Kustomize in addon operators

- docs/addon/walkthrough/README.md
- examples/guestbook-operator/Dockerfile
- examples/guestbook-operator/Makefile
- examples/guestbook-operator/controllers/guestbook_controller.go
This PR updates `docs/addon/walkthrough/README.md` contents to implement guestbook-operator, instead dashboard-operator.
related to: #80
> Update walkthrough doc to implement guestbook-operator

- pkg/patterns/addon/pkg/loaders/types.go
We fail otherwise if there are directories in the manifests directory.
> FSLoader: Don't try to read directories

- pkg/patterns/declarative/reconciler.go
- pkg/test/golden/validator.go
The manifest built by Kustomize doesn't include the OwnerRefs. Due to this, the manifest built by Kustomize doesn't reconcile with the operator. 
This PR ensures reconciliation by parsing the manifest created by Kustomize into objects and then injecting the OwnerRef needed for Reconcile.
> Add ownerRef into kustomize build

- utils/utils.go
> Moves some functions from Coredns operator that could be reused 

- hack/ci/fetch_kubebuilder_release_bin.sh
- hack/ci/test.sh
- hack/smoketest.go
- pkg/patterns/addon/pkg/loaders/http.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/exec.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
- pkg/test/mocks/cache.go
- pkg/test/mocks/manager.go
- utils/utils.go
This commit modifies CI test to fetch kubebuilder release binary before test runs.
This enables to run go test using [envtest package from kubernetes-sig/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/envtest).
> Modify CI Test to Fetch kubebuilder Release Binary

- docs/addon/walkthrough/README.md
- go.mod
- go.sum
- pkg/patterns/declarative/metrics.go
- pkg/patterns/declarative/metrics_test.go
- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
This commit
* adds two metrics
- Count the number of reconciliation & failure of reconciliation
- Track the number of objects in manifest
* modifies walkthrough example to mention this metrics functionality
* and deletes
* reconcilerParams.groupVersionKind option
* WithGroupVersionKind function
Added two metrics are registered to controller-runtime Prometheus registry
This PR is related to #65 .
> Add Reconciliation Metrics Functionality

- .gitignore
Now that we are using go.mod and not shipping the vendor directory, we
no longer want to ignore those files (as they shouldn't exist).
> .gitignore: don't ignore vendor

- .github/workflows/main.yml
set-env is deprecated for security reasons, so move to the new GITHUB_ENV approach.
> github actions tests: replace set-env with GITHUB_ENV

- .github/workflows/main.yml
- docs/addon/walkthrough/README.md
- go.mod
- go.sum
- pkg/patterns/addon/pkg/loaders/types.go
- pkg/patterns/addon/pkg/status/version.go
- pkg/patterns/declarative/pkg/manifest/patch.go
This commit updates dependencies
- deps: bump controller-runtime to v0.7.0 and other deps to their >v1 module path, and go to version 1.15
- pkg/patterns: update >v1 module paths
> deps: controller-runtime v0.7.0, go 1.15, other deps to >v1 paths

- utils/utils.go
> utils/utils.go: GetDNSDomain() processes the correct CNAME value

- go.mod
- pkg/test/golden/validator.go
- utils/utils.go
Go 1.13's `fmt.Errorf()` has wrapping functionality that was achieved using non-std packages prior to that version, which can now be removed.
> *: remove non-std library errors packages

- pkg/patterns/declarative/sort.go
Namespaces need to be created before any other resources, such as ServiceAccount.
> Add Namespace to the sort function

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR add template files for issue and PR on GitHub.
It's good to clarify information about issue and PR.
I referred k/k's templates for issue and PR.
But that is too much input items for this repository I think, I cut some items from it for ease to input.
> Add template for issue and PR

- go.mod
- go.sum
- pkg/patterns/declarative/pkg/manifest/objects_test.go
This PR adds some unit tests for `objects.go` because that has some core functions for this framework.
It's good to increase coverage for framework.
This PR doesn't have enough coverage, so I'll update to add more unit tests for `objects.go`.
> Add unit tests for objects.go

- go.mod
- go.sum
- pkg/patterns/declarative/watch_test.go
This PR adds unit tests for `watch.go`
As of now part of tests are implemented, I'll add additional tests.
related to: #150
> Add tests to watch.go

- pkg/patterns/declarative/sort.go
This PR changes Secrets with Secret in `sort.go`.
That's because kind of secret is `Secret` not `Secrets`.
related to: #152
> Change Secrets with Secret in sort.go

- pkg/patterns/declarative/reconciler.go
This has been logging erroneous not found errors since the returned
error wraps the not found error.
> Unwrap error when checking for not found.

- OWNERS_ALIASES
To help shepherd in kubebuilder-related PR's like #160 (mostly k8s version bumps).
> OWNERS_ALIASES: add estroz

- OWNERS_ALIASES
As per
https://groups.google.com/g/kubebuilder/c/-5hOFa_adr4/m/Sp_Zb755AwAJ,
directxman12 is stepping down.
> Remove directxman12 from OWNERS

- pkg/patterns/declarative/pkg/applier/type.go
- pkg/patterns/declarative/reconciler.go
Rename Applier interface method from `Applyx` to `Apply` and embed
the Applier interface in the `kubectlClient` interface.
> Embed Applier interface in kubectlClient interface 

- go.mod
- pkg/patterns/declarative/pkg/manifest/objects_test.go
- pkg/patterns/declarative/watch_test.go
This PR changes assert library with `github.com/google/go-cmp/cmp` library.
This is because for fitting to google go style guide, [commented here](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/151#discussion_r598306087).
None
None
None
> Change assert library with cmp library in test

- pkg/patterns/declarative/reconciler.go
Otherwise apierrors.IsNotFound does not work correctly, and we spam a
misleading error message.
> GetObjectFromCluster should preserve error chain

- pkg/patterns/declarative/pkg/watch/dynamic.go
Though we don't use the bookmark resource version, this should help us
keep the watch connections alive (avoid any TCP timeout issues).
> Allow watch bookmark events

- docs/addon/walkthrough/README.md
- examples/guestbook-operator/controllers/guestbook_controller.go
- pkg/patterns/declarative/pkg/watch/dynamic.go
- pkg/patterns/declarative/watch.go
Though this is a breaking change, reusing the RESTMapper avoids repeated discovery.
Also mark the watch functions as deprecated to support a future move to an internal package.
> Re-use the RESTMapper from the ctrl.Manager in the dynamic watcher

- .github/workflows/main.yml
This PR updates golang version to 1.16 in github workflow files.
GitHub workflow job `CI / verify-gomod (pull_request)` fails in #169. 
[Failure detail log here](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/169/checks?check_run_id=3503792196)
That PR update go version to v1.16 in go.mod, but specified version in workflow is set to [v1.15](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/1f796d48dfcd38bf1a74bba3dd60f80bf094a995/.github/workflows/main.yml#L42).
Github workflow job failure in #169 will be fixed once this PR merged, I think.
> Update go1.16 in github workflow

- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/exec.go
- pkg/patterns/declarative/pkg/applier/exec_test.go
- pkg/patterns/declarative/pkg/applier/type.go
- pkg/patterns/declarative/reconciler.go
The direct-applier was not setting the namespace correctly; we reuse
the SetNamespace visitor to do so.
> Fix namespace setting with direct applier

- docs/addon/walkthrough/README.md
This PR adds missing kubebuilder flag ``--repo`` in walkthrough example code
> Fix missing kubebuilder flag in walkthrough

- docs/addon/walkthrough/README.md
This PR updates walkthrough docs to fit latest code.
Recently, apply logic in kubebuilder-declarative-pattern is updated by #173,
that why we need to update documentations.
And I added that removing `spec.foo` key in `config/samples/addons_v1alpha1_guestbook.yaml`.
Related to #176
> Update walkthrough docs to fit latest code

- hack/smoketest.go
- pkg/patterns/addon/pkg/loaders/git.go
- pkg/patterns/addon/pkg/loaders/http.go
- pkg/patterns/addon/pkg/loaders/types.go
- pkg/patterns/declarative/metrics_test.go
- pkg/patterns/declarative/pkg/applier/exec_test.go
- pkg/test/golden/validator.go
Cleanup deprecated ioutil and use io and os instead
Fixes #
> Use io and os in favor of ioutil

- pkg/patterns/declarative/reconciler.go
Before this fix, a declarative controller using `declarative.WithOwner(declarative.SourceAsOwner)` will end up in an infinite reconciliation loop if any of the manifests in the package do not support having the declarative object as its owner.
For example, consider a _namespaced_ declarative object `foo/foo` of type `Foo`, installing a package that adds a few objects (say, two `Bar`s) in the same namespace plus another object (say, a `Baz`) in a fixed namespace `qux`. With the old behavior of this reconciler, the following happens:
1. The reconciler creates all objects in the package, setting owner references to an object with the same group, version, kind and name as the declarative object, and the same namespace as each respective object from the …
> Skip setting owner refs for objects that don't support it

- pkg/patterns/declarative/pkg/manifest/patch.go
This reduces the logspam around "applied 0 patches"
> Early-exit when applying no patches

- pkg/patterns/declarative/pkg/watch/dynamic.go
Exit if we get an error notification.
Check for duplicate messages and suppress them, as they are all going
into the same channel.  This avoids renotification when the watch
connection is dropped.
> Improve watch event handling

- pkg/patterns/declarative/pkg/watch/dynamic.go
> Avoid concurrent writes to a map in dynamicWatch

- pkg/test/mocks/client.go
This adds a `FakeStatusClient` with noop implementations of `Update` and `Patch`, to enable doing things like `client.Status().Update(...)` in methods being tested.
I don't know if there was any special reason this was not already in place, other than "it hadn't been needed yet" - if there are any special considerations that need to be taken care of when updating status, this PR might not be good enough. But given that `FakeClient.Update` and similar methods also just `return nil`, this should probably be OK for most use cases.
> Implement a fake status client for testing

- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/addon/pkg/status/kstatus.go
- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/status.go
related with #197: 
1. refractory mechanism of updating status:
a. allow status `Reconciled` method known if `error` happened, so that user could be able to submit an error to CR status field or launch an Event;
b. maybe it's related with #190 
Fixes #
> refactory updating status mechanism, status func could handle error

- pkg/patterns/declarative/pkg/manifest/patch.go
Store the name of the base object, because this name may have been munged.
Apply this name to the patched object.
Fixes #
[StrategicMergePatch](https://github.com/kubernetes/apimachinery/blob/df993592a122931b8aac4db57689e09458a2332c/pkg/util/strategicpatch/patch.go#L812).
> refactor: Use strategic merge patch

- pkg/patterns/declarative/labels_test.go
This PR adds unit tests for `pkg/patterns/declarative/labels_test.go`.
NONE
NONE
I would like to add unit tests for package `pkg/patterns/declarative` because of this package has many manipuration logics of this repository.
> Add unit test for declarative/labels

- pkg/patterns/addon/pkg/loaders/types_test.go
This PR adds more unit tests for `pkg/patterns/addon/pkg/loaders/types.go`.
As of now, this repository should have more unit tests, because of codebase quality and readability for logics which already exists.
> Add unit test for loaders/types

- go.mod
- pkg/patterns/addon/pkg/loaders/types_test.go
- pkg/patterns/declarative/reconciler.go
- pkg/test/golden/validator.go
This PR replace `kustomize/api/filesys` with `kustomize/kyaml/filesys` because of [`kustomize/api/filesys` is deprecated now](https://github.com/kubernetes-sigs/kustomize/pull/3997).
NONE
NONE
NONE
> Use kustomize/kyaml/filesys

- pkg/patterns/addon/pkg/loaders/fs_test.go
This PR adds more unit tests for `pkg/patterns/addon/pkg/loaders/fs.go`.
NONE
NONE
related to: #205
> Add unit test for loaders/fs

- pkg/patterns/declarative/pkg/applier/direct.go
A not so pretty solution for https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/201, more like a temporary workaround.
I think it would be nicer to use `ApplyOptions` directly instead of the internal `ApplierOptions` type, but this would break compatibility with ExecApplier.
Fixes [#201](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/201)
> Propagate applyOpts extraArgs

- docs/releases/release-0.12.md
- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/addon/pkg/status/kstatus.go
- pkg/patterns/addon/pkg/status/version.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/watch.go
This allows changing them - in particular setting the namespace.
Without this if the Namespace field was changed, it would not be
reflected in the underlying object.
This is also more similar to unstructured.Unstructured, which we are
modelling after.
Also proposing that we think of this as the first breaking change for 0.12.  We can continue to cherry-pick back to 0.11 though!
> Introduce setters for name and namespace

- pkg/patterns/declarative/reconciler.go
if `metadata.namespace` on Cluster-level resource(such as ClusterRole) is set, `kubectl apply` will not report an error and just ignore it. But when I submit via Controller, it failed and report an error like `resource xxx is not found`. 
After some time I dug, I realize that `namespace` is joined into the URL. So maybe we should check whether the resource is Cluster-level, and ignore `metadata.namespace` if it's positive.
Fixes #
> check object scope before fetching

- examples/guestbook-operator/channels/packages/guestbook/0.1.0/kustomization.yaml
- examples/guestbook-operator/controllers/guestbook_controller.go
- pkg/patterns/declarative/reconciler.go
If there are multiple resources in a manifest, and `WithApplyKustomize` option is used, the resulting manifests to apply would only contain the last item from the manifest. This PR corrects this, and takes into account that a manifest could contain multiple resources.
> Allow multiple resources in manifest files when using kustomize

- pkg/patterns/declarative/reconciler.go
1. allow CR to decide whether to enable pruning resources;
2. allow CR to decide what kinds of resources should be pruned.
Fixes #
introduce 2 interfaces to let CR can decide whether and how to prune resources. When none of them are implemented, the behavior should be the same as before. So I think this is not a breaking change.
> enhance handling prune for CR

- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
`initContainers` of Pod are not mutated.
Fixes #
> mutating image of Pod should include initContainers

- pkg/mocks/mockkubeapiserver/apiserver.go
- pkg/restmapper/caching.go
- pkg/restmapper/controllerrestmapper.go
- pkg/restmapper/controllerrestmapper_test.go
The default RESTMappers are very optimized around the kubectl use-case, where most of the time controllers only need to map GVK -> GVR to support an apply operation.
Start adding a RESTMapper optimized around this specific use-case.
> RESTMapper optimized for controllers

- pkg/patterns/declarative/pkg/applier/direct.go
1. When I apply CR with it's CRD, an error like `resource <Kind> is not found` will return. 
2. In fact, `kubectl` will try its best efforts to apply YAMLs. In the progress, maybe CRDs have not been established and an error could return. But in the next retry, all YAMLs can be applied successfully.
ref: https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/apply/apply.go#L438
Fixes #
> try apply yaml in best efforts

- pkg/patterns/declarative/pkg/applier/direct.go
This PR sets filename field with dummy name for appling manifest.
Before this PR, operator said errors followings:
`ERROR   applying manifest       {"error": "error getting apply options: must specify one of -f and -k"}`
I checked that this PR fixed current bug, but it's pretty rough, I think.
Fixes #224
Currently, update is pretty rough, but root cause is discovered.
Feel free to comment more good approach.
NONE
> Set dummy name for apply on direct.go

- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
```
previous doc
--- # THIS IS A COMMENT
---   
really doc here
```
below YAML separator is valid for `kubectl` but does not work in this repo.
1. the first separator has some comments.
2. the second separator has white space at the end of it.
In current behavior, `really doc here` will treat as a part of `previous doc`, and `really doc here` will be eaten in `yaml.Unmarshal` later.
Fixes #
> fix decode multi YAML doc

- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
Add some test cases for the empty object cases, as these have been
problematic in the past.
> Parsing: add more empty test cases

- pkg/patterns/declarative/reconciler.go
This commit fixes an issue where `Reconcile()` can return a nil `err`,
even if an error occured during execution, as long as the `status`
option is not nil.
This bug effectively hid from callers of `Reconcile()` if an error
occurred.
Fixes #
This issue seems to have originated from https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/199.
> Fix bug where Reconcile() returns nil err if status option is not nil

- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/direct_test.go
This PR adds unit tests for direct applier in `direct.go`.
`direct.go` doesn't have tests as far, we should add tests for prevent degrades.
For implimenting tests, this PR changes direct applier to have some delegation structures.
It is [the same manner with that in `exec.go`](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/2072cf081b2e512b687c6bf152466646df1ac2c9/pkg/patterns/declarative/pkg/applier/exec.go#L31-L51)
Related to [#201 comment](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/201#issuecomment-1185585708)
None
None
> Add unit test for direct applier

- pkg/mocks/mockkubeapiserver/apigrouplist.go
- pkg/mocks/mockkubeapiserver/apiresourcelist.go
- pkg/mocks/mockkubeapiserver/apiserver.go
- pkg/mocks/mockkubeapiserver/apiversions.go
- pkg/mocks/mockkubeapiserver/controllers.go
- pkg/mocks/mockkubeapiserver/getresource.go
- pkg/mocks/mockkubeapiserver/memorystorage.go
- pkg/mocks/mockkubeapiserver/openapi_request.go
- pkg/mocks/mockkubeapiserver/patchresource.go
- pkg/mocks/mockkubeapiserver/postresource.go
- pkg/mocks/mockkubeapiserver/putresource.go
- pkg/mocks/mockkubeapiserver/request.go
- pkg/mocks/mockkubeapiserver/testhelpers.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/direct_test.go
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/manifest.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/before.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/manifest.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/before.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/manifest.yaml
- pkg/restmapper/controllerrestmapper_test.go
- pkg/test/httprecorder/http_recorder.go
- pkg/test/httprecorder/request_log.go
- pkg/test/testharness/golden.go
- pkg/test/testharness/harness.go
Create some golden tests to try to make sure our apply library is reasonably efficient / so we can track what it is doing.
- tests: Improve mock kubeapiserver, introduce test for direct Applier
- tests: record and validate the requests we are making
- tests: add test for when objects already exist
- tests: add test for the case when last-applied is present
> More mock testing

- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/direct_test.go
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/expected.yaml
- pkg/test/httprecorder/request_log.go
We don't normally need it, and it is expensive to fetch.  Use ApplyOptions directly rather than going through the kubectl abstraction layer (which always fetches the OpenAPI)
Builds on #246
> Direct applier: Avoid fetching OpenAPI

- mockkubeapiserver/putresource.go
This is what the real apiserver does, and it's important because it
means we don't send another watch notification / don't update the
resourceVersion.
> mockkubeapiserver: don't update if the object doesn't change

- mockkubeapiserver/putresource.go
We were trying to avoid spurious updates, but we ended up ignoring all
updates (?).
> mockkubeapiserver: fix bug where comparing wrong objects

- pkg/patterns/declarative/pkg/applier/applylib.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/exec.go
- pkg/patterns/declarative/pkg/applier/testdata/applylib/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/applylib/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/applylib/simple3/expected.yaml
- pkg/patterns/declarative/pkg/applier/type.go
- pkg/patterns/declarative/reconciler.go
We use the force option quite a lot, so we need to support it.
Also nudge away from ExtraArgs towards explicit options.
> applylib: Recognize and map the --force kubectl option

- mockkubeapiserver/patchresource.go
- pkg/patterns/declarative/reconciler.go
Otherwise it's difficult to track down what has gone wrong.
This may lead to over-eventing (if we've already recorded the error),
but we can deal with that problem when we come to it!
> Record event when reconciler fails unexpectedly

- applylib/go.mod
- applylib/go.sum
- examples/guestbook-operator/go.mod
- go.mod
- go.sum
These make our submodules hard to consume as a library.
go.work is the latest approach that is recommended instead for local
development.
I think this does mean we will need to structure commits separately
across the libraries, but that may be acceptable.
> Stop using go.mod replace directives

- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
Not doing so makes it harder to build options outside of the call,
because we can't declare a []reconcilerOption unless it is exported.
> Export ReconcilerOption

- pkg/patterns/declarative/annotations.go
- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
I had a use case for setting annotations on all objects in an object transform, and found that while we do have `AddLabels` that does this, there's no corresponding `AddAnnotations`.
There _is_ a way to do this without this PR, since the `manifest.Object` exposes `UnstructuredObject()` to get at the underlying `unstructured.Unstructured`, but its docstring states
> UnstructuredContent exposes the raw object, primarily for testing
so I figured it's better to not ask users to take a dependency on that.
> Add AddAnnotations companion to AddLabels

- pkg/patterns/declarative/pkg/applier/direct.go
We lost the default value in #247, which is a regression that prevents
some changes from going through.
> Set Overwrite in ApplyOptions

- pkg/patterns/declarative/metrics_test.go
- pkg/patterns/declarative/pkg/applier/applylib.go
- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/direct_test.go
- pkg/patterns/declarative/pkg/applier/exec.go
- pkg/patterns/declarative/pkg/applier/exec_test.go
- pkg/patterns/declarative/pkg/applier/type.go
- pkg/patterns/declarative/reconciler.go
In theory a breaking change, but should not break anyone and avoids
reparsing and confusion over JSON vs YAML input formats.
This fixes a bug in the new applyset applier where we were expecting YAML but getting JSON.  That applier is not the default and is only on the dev/main branch, so no backports needed, thankfully!
> Change ApplierOptions to take Objects, not a manifest.

- applylib/testutils/harness.go
- mockkubeapiserver/patchresource.go
- mockkubeapiserver/postresource.go
- mockkubeapiserver/putresource.go
- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/patterns/declarative/pkg/applier/exec.go
- pkg/test/httprecorder/http_recorder.go
- pkg/test/testharness/golden.go
As of Go 1.16, funcs related to operate files and directories in [the ioutil pakage are deprecated](https://pkg.go.dev/io/ioutil).
This PR replaces deprecated funcs on ioutil by using io and os packages.
/kind cleanup
NONE
NONE
NONE
> Replace deprecated funcs on ioutil package

- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
- pkg/test/httprecorder/request_log.go
To avoid spurious failures from concurrent requests, we sort
consecutive API discovery requests alphabetically.
> tests: normalize http request order

- bin/.gitignore
- dev/update-golden
- hack/ci/test.sh
- pkg/patterns/declarative/pkg/applier/exec_test.go
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
Update hack/ci/test.sh to download kubectl and add it to the path.
Add dev/update-golden to generate golden output with the kubectl version.
We run with kubectl 1.26 so that we get the fast-discovery, as this is
expected to roll out more generally over the next few months.
> tests: run with a known version of kubectl

- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
This PR makes the CascadingStrategy added in https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/274 configurable, adding a new option `withCascadingStrategy` and making sure that `Foreground` is the default if not set.
We need it to configure different CascadingStrategies for main and test
Fixes #
I have not seen proper tests I could test this with. Are there some?
I ran this with the controller I am working on.
> add option to configure cascading strategy

- mockkubeapiserver/memorystorage_watch.go
Otherwise we don't handle errors writing to the watch stream
correctly.
> mockkubeapiserver: populate errChan

- docs/addon/walkthrough/README.md
```
2023/01/04 15:52:14 failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.17' is incompatible because 'requires 1.13 <= version < 1.17'. You can skip this check using the --skip-go-version-check flag
```
Fixes #
> Update README about required go version

- mockkubeapiserver/apiserver.go
An endpoint I had previously missed!
> mockkubeapiserver: support get of cluster-scoped object

- mockkubeapiserver/listresource.go
- mockkubeapiserver/memorystorage_watch.go
controller-runtime seems to have some bugs around apiservers that
don't support this, so introduce a minimal implementation.
> mockkubeapiserver: support PartialObjectMetadata watches

- mockkubeapiserver/request.go
This allows for more predictable output, as otherwise the length is
only sometimes sent (maybe varying by go version)
> mockkubeapiserver: Always send content-length

- pkg/test/httprecorder/request_log.go
- pkg/test/testreconciler/simpletest/controller_test.go
We recognize (and sort) more group-discovery requests - now that we
have them - so that golden test output can tolerate parallel/random
discovery as done by kubectl.
> Normalize more discovery requests

- mockkubeapiserver/apiresourcelist.go
Should ensure more predictable test results.
> Sort APIResources into a consistent order

- mockkubeapiserver/listresource.go
This mirrors reality and allows us to synchronize on watch messages.
> mockkubeapiserver: send header of watch eagerly

- examples/guestbook-operator/channels/packages/guestbook/0.1.0/manifest.yaml
- examples/guestbook-operator/controllers/tests/patches-stable.out.yaml
- examples/guestbook-operator/controllers/tests/simple-stable.out.yaml
**What type of PR is this?**
/kind cleanup
This PR replaces all `k8s.gcr.io` references with `registry.k8s.io`. See the linked issue for more details.
xref https://github.com/kubernetes/k8s.io/issues/4738
**Release note**:
```
Replace all `k8s.gcr.io` references with `registry.k8s.io`
```
> Replace k8s.gcr.io with registry.k8s.io

- pkg/patterns/addon/pkg/status/kstatus.go
The k-d-p  object should set `status.healthy=true` if all manifests are reconciled. Right now if the previous reconcile is unhealthy, this field will show "healthy=false" even if the latest reconcile is healthy.
> reset status.healthy in each reconcile

- pkg/patterns/declarative/hooks.go
- pkg/patterns/declarative/reconciler.go
- pkg/test/testreconciler/simpletest/controller.go
We sleep briefly (100ms) after updating the status.
This is a hack to ensure that we see the watch event, because
otherwise we can start a re-reconcile based on our derived objects,
and then reconcile again based on our own status update.
This is racy behaviour and causes non-determinism which breaks our
golden tests.
We do this only in this test controller, but maybe we should have
similar logic to "debounce" in all controllers.
Fixes #
> testreconciler: pause after reconciliation

- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/test/httprecorder/http_recorder.go
- pkg/test/httprecorder/request_log.go
When kubectl was doing discovery in parallel, we would often drop
requests from the log.  Add a mutex to protect against this (and
generally to make it more correct)
> tests: fix race when recording concurrent requests

- pkg/restmapper/caching.go
- pkg/restmapper/controllerrestmapper.go
This function is needed for mapping from a group kind
to a group version kind, which will be needed for pruning.
> controllerrestmapper: implement RESTMappings

- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/statusinfo.go
Fixes a recent regression where we would not return errors from reconcileExists.
> Remove named return values in reconciler

- applylib/applyset/applyset.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
This pull request fixes an issue where the `updateParentLabelsAndAnnotations` function always updates the parent object. This was due to the `applyset.kubernetes.io/tooling` annotation being set to a different value in the kubectl apply package than what the apply set applier expected.
> fix: use apply set tooling in apply set applier

- .github/workflows/main.yml
- pkg/patterns/declarative/metrics.go
- pkg/test/testreconciler/simpletest/controller.go
This PR fixes the CI "verify-goimports" and "verify-gomod" which the CI go 1.19 cannot run `go mod tidy` for k-d-p go 1.20 modules.  This currently blocks any upcoming PRs to pass the CI check.
> fix: bump ci go to v1.20 and fix goimports

- mockkubeapiserver/memorystorage_watch.go
This PR fixes a data race issue in test where two threads in MockKubeAPIserver memorystorage read/write to the same `resourceInformation`
** Verify**
With this PR, the following command should no longer give the data race warning (see data race log)  
```
go test -race sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative
```
data race log
```bash
WARNING: DATA RACE
Write at 0x00c000792d50 by goroutine 112:
runtime.mapaccessK()
/usr/local/go/src/runtime/map.go:518 +0x1ec
sigs.k8s.io/kubebuilder-declarative-pattern/mockkubeapiserver.(*MemoryStorage).CreateObject()
/Users/yuwenma/go/src/sigs.k8s.io/kubebuilder-declarative-pattern/mockkubeapiserver/memorystorage.go:194 +0x204
sigs.k8s.io/kubebuilder-declarative-pattern/mockkubeapiserver.( …
```
> fix: mockapiserver data race in create memorystorage

- applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/applyset.go
- applylib/third_party/forked/k8s.io/apimachinery/pkg/util/sets/empty.go
- applylib/third_party/forked/k8s.io/apimachinery/pkg/util/sets/ordered.go
- applylib/third_party/forked/k8s.io/apimachinery/pkg/util/sets/set.go
- commonclient/doc.go
- commonclient/factory_cr11.go
- commonclient/factory_cr15.go
- commonclient/restmapper_cr11.go
- commonclient/restmapper_cr15.go
- pkg/patterns/declarative/metrics.go
- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/patterns/declarative/pkg/applier/global.go
- pkg/patterns/declarative/pkg/applier/global_without_kubectl.go
- pkg/patterns/declarative/watch.go
- pkg/restmapper/controllerrestmapper.go
- pkg/restmapper/controllerrestmapper_cr11.go
- pkg/restmapper/controllerrestmapper_cr15.go
- pkg/restmapper/controllerrestmapper_test.go
- pkg/test/testreconciler/simpletest/controller.go
Create an abstraction layer so that we are less dependent on a particular version of client-go / controller-runtime.  The intent here is that controllers can work with multiple versions of client-go/controller-runtime, and thus a wide range of k8s versions.
- Make our applyset not depend on generics
- Create commonclient to abstract controller-runtime versions
> Create abstraction layer over controller-runtime/client-go versions

- applylib/applyset/applyset.go
- applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/applyset.go
- applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/applyset_pruner.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
A comparable change is being made in kubectl also; kind is clearer for
end-users, and this enables creation of a CRD and an instance of the
CRD in one applyset.
> applyset: Switch to contains-group-kinds annotation

- applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/applyset.go
As suggested in prior code review.
> Cleanup: remove commented-out code in kubectl fork

- examples/guestbook-operator/Makefile
This change fixes the example guestbook operator Makefile by allowing the `controller-gen` and `kustomize` tools to be successfully installed.
Previously any Make commands requiring one of these tools such as `make generate` would fail since the `go-get-tool` function would only download the package with go get however not install the package with go install, where go get no longer installs executables since Go 1.17, https://go.dev/doc/go-get-install-deprecation.
The updated Makefile commands for `controller-gen` and `kustomize` aligns with the Makefile kubebuilder generates for new projects, https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile.
> chore: allow tools to be installed with newer versions of go

- mockkubeapiserver/apiserver.go
- mockkubeapiserver/hooks/crd.go
- mockkubeapiserver/storage/memorystorage/crd.go
Simulate the CRD being accepted into the apiserver and this being
reflected into status, for clients that check status.
Also fix a nil-pointer error due to lack of proper initialization.
> mockkubeapiserver: ensure CRDs become ready

- commonclient/metrics_cr11.go
- commonclient/metrics_cr16.go
- examples/guestbook-operator/main.go
- pkg/patterns/declarative/metrics_test.go
- pkg/test/testreconciler/simpletest/controller_test.go
This PR makes the code backwards-compatible with versions of controller-runtime before 0.16, which introduced the [metrics/server](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.16.3/pkg/metrics/server) package that kdp now uses. The PR uses `//go:build` to segregate handling of the metrics configuration depending on the version of controller-runtime.
N/A
The following links may be useful references
* When kdp updated to controller-runtime v0.16: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/352
* Previous example of `//go:build` usage: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/342
* Usage of metrics/server in codebase: …
> Enable backwards-compatibility with controller-runtime v0.15

- pkg/patterns/declarative/pkg/applier/applylib.go
- pkg/patterns/declarative/reconciler.go
Include the case when we're using a typed object.
> Extract GVK more robustly when building applyset parent

- pkg/patterns/declarative/pkg/applier/applylib.go
- pkg/patterns/declarative/pkg/applier/type.go
This allows us to override the dynamic client, useful for tests or if
we want to intercept and track all the calls (for automatic dependency
tracking).
> Allow dynamic client to be set

- pkg/patterns/addon/pkg/status/kstatus.go
This PR extends the kStatusAggregator to support user supplied gvk specific compute and abnormal conditions functions allowing users to support aggregate status without implementing an entire build status method.
Details and summary documented in [issue 365](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/365)
Fixes #365 
> feat: kStatusAggregator user supplied gvk compute and abnormal conditions fns

- commonclient/factory_cr11.go
- commonclient/factory_cr15.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/type.go
- pkg/patterns/declarative/reconciler.go
Should be slightly more efficient via better HTTP connection reuse.
> Optimization: Reuse HTTPClient / DynamicClient in reconcile

- pkg/patterns/declarative/watch.go
By using ForConfigAndClient, we are more likely to reuse the http connection.
We expose an HTTPClient, but also we default to the manager HTTPClient.
> Allow http client reuse in dynamic client

- pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
https://book.kubebuilder.io/reference/markers/crd-processing
Currently, a MOSS controller does not support patches correctly by default. For example, applying the following object would get an error `strict decoding error: unknown field "spec.patches[0].apiVersion", unknown field "spec.patches[0].kind", unknown field "spec.patches[0].metadata", unknown field "spec.patches[0].spec"`.
```
apiVersion: configdelivery.gke.io/v1beta1
kind: ConfigSync
metadata:
name: config-sync
spec:
version: 1.16.1
patches:
- apiVersion: apps/v1
kind: Deployment
metadata:
name: reconciler-manager
namespace: config-management-system
spec:
template:
spec:
containers:
- name: reconciler-manager
resources:
limits:
memory: "1Gi"
```
To fix this, we need to add `x-kubernetes-preserve-unknown-fields: true` into the …
> Add a kubebuilder marker to patches to preserve unknow fields

- pkg/patterns/declarative/reconciler.go
A common pattern in our operators is to use preflight checks to call out to some external system for more information (that can be written e.g. to the status of the `DeclarativeObject`) or to validate that some property of the `spec` meets requirements to be able to expand the channel manifests. If the check fails, sometimes the right behavior is to requeue with backoff - but
often it's not: e.g., if the spec is deemed invalid, there's no reason to requeue the resource. If spec changes we'll get a new event anyway, and until spec changes we won't be able to reconcile.
There is already a `ErrorResult` type that can be used in a Preflight implementation to signal what we want the reconciliation function to return, but it's currently not being …
> Respect ErrorResults returned from preflight checks

- pkg/patterns/declarative/image.go
- pkg/patterns/declarative/image_test.go
- pkg/patterns/declarative/pkg/manifest/objects.go
CronJob has a different path to the PodSpec from the other currently supported types of ImageRegistryTransform. This fixes the image transform logic to find the correct path.
**What this PR does / why we need it**: The `ImageRegistryTransform` used for private registries supports a few enumerated types, including `CronJob`. The same `PodSpec` path is used for all types, however `CronJob` has a different path. This change adds special handling for the `CronJob` case.
**Which issue(s) this PR fixes**: N/A
**Special notes for your reviewer**: N/A
**Additional documentation**: N/A
> fix: use correct path to PodSpec for CronJob

- mockkubeapiserver/hooks/crd.go
- mockkubeapiserver/hooks/deployment.go
- mockkubeapiserver/patchresource.go
- mockkubeapiserver/postresource.go
- mockkubeapiserver/putresource.go
- mockkubeapiserver/storage/memorystorage/memorystorage.go
- mockkubeapiserver/storage/memorystorage/resourceinfo.go
- mockkubeapiserver/storage/resourceinfo.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Aiming for a little bit more fidelity, also enables us to test
observedGeneration (in future).
> mockkubeapiserver: set generation on objects

- pkg/patterns/declarative/pkg/watch/dynamic.go
Allow setting shorter watch timeout for the first time alone.
**What this PR does / why we need it:**
We have seen in some evnironments (where requests are tunnelled) setting up the (first) watch is blocking if there are no resources available to watch. This causes the apply loop to be blocked when setting up watches before apply.
> Add the ability to set watch timeouts.

- applylib/applyset/applyset.go
- applylib/applyset/health.go
- applylib/applyset/results.go
Expose more health info as well as counts in Apply results
When using applyset as a library we sometimes want more information about the last applied set.
Currently we get boolean (IsHealthy, IsAllApplied).
Having more is useful when consuming this as a library.
> Expose more health info as well as counts in Apply results

- applylib/applyset/applyset.go
- applylib/applyset/health.go
- go.work.sum
We want to provide applyset users a way to plugin their own status compute logic. 
This helps with adding custom status compute for objects not supported by `kstatus` library.
> Add a callback option to applyset to compute Health of applied objects

- applylib/applyset/applyset.go
- applylib/applyset/health.go
- applylib/applyset/results.go
Capture error as part of health computation and propagate it to health tracker. This will be returned to the caller as part of object result
> propagate error that occurs during health computation

- applylib/applyset/applyset.go
- applylib/applyset/results.go
This PR return the last applied objects in status. 
This is useful for controllers that need access to applied objects. 
It avoids a Get() call on the controller.
> Return the last applied object in status

- pkg/patterns/declarative/pkg/applier/direct.go
This will fix the  "annotation too long" problem when the managed manifests are too large.
Fixes #
> feat: Enable server-side-apply on direct applier

- applylib/go.mod
- dev/codebots/update-golang-version
- examples/guestbook-operator/Dockerfile
- examples/guestbook-operator/go.mod
- go.mod
- ktest/go.mod
- mockkubeapiserver/go.mod
- **chore: create script to update golang**
- **codebot: update go to 1.23.5**
> chore: script to update golang; update go to 1.23.5

- .github/workflows/main.yml
This avoids needing to update the go version in multiple places.
> chore: get go version from go.mod

- docs/project-management/branching-and-versioning.md
We want to be more systematic about our branching / versioning.
Document the process we were (trying to) follow.  We can also
automate some of the toil here.
> docs: document our branching / versioning process

- go.work.sum
- pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/addon/pkg/status/kstatus.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
This updates the built in CommonStatus struct to provide observedGeneration behavior when using one of the provided status builders. Custom implementations of the BuildStatus interface could already set observedGeneration if desired, but this provides an opinionated default to the addon implementations.
**What this PR does / why we need it**: Sets `status.observedGeneration` for the built-in `CommonStatus` type. This makes it easier to determine when a KDP controller which uses the Addon object has reconciled the current spec of the managed resource.
Fixes #391
> feat: add observedGeneration to CommonStatus

- pkg/patterns/addon/pkg/utils/helpers_test.go
- pkg/patterns/declarative/reconciler.go
This PR add a new InitWithName function that allow passing in a custom controller name, and changes the default name to be inferred from the prototype when possible.
It's my first contribution and first time with Go so reviews are welcome.
Change should simple enough to be self explanatory.
> derive controller name from prototype and allow custom name
