- README.md
We'll remove when the WIP issue is resolved.
> README: add a temporary warning sign

- examples/dashboard-operator/channels/packages/dashboard/1.8.3/manifest.yaml
- examples/dashboard-operator/config/crds/app_v1beta1_application.yaml
- examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
- pkg/patterns/addon/application.go
- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/declarative/application.go
- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/pkg/kubectlcmd/client.go
- pkg/patterns/declarative/pkg/manifest/objects.go
The Application is a CR that represents a given deployment. If a
deployment contains an Application we can specialize it based on the
declarative configuration. We can go further with Addons which have
health/version to expose on the Application.
More info on the application: https://github.com/kubernetes-sigs/application
fixes #5
> Implement Application management

- examples/dashboard-operator/pkg/controller/dashboard/tests/simple.out.yaml
- pkg/patterns/declarative/labels.go
> declarative: generate lowercase labels in SourceLabel

- README.md
- pkg/patterns/addon/doc.go
- pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
- pkg/patterns/addon/pkg/apis/v1alpha1/doc.go
- pkg/patterns/addon/pkg/loaders/doc.go
- pkg/patterns/addon/pkg/loaders/fs.go
- pkg/patterns/addon/pkg/status/doc.go
- pkg/patterns/declarative/doc.go
Remove the scary, 'we're gonna change this all!' heading as things have
pretty well landed in the repo. We will be evolving but structrually the
repo is in good shape.
> docs: Remove warning, add more godocs

- docs/addon/walkthrough/README.md
Signed-off-by: Haiyan Meng <haiyanmeng@google.com>
> Update the `Running on-cluster` section

- docs/addon/walkthrough/README.md
Remove the line to avoid exception `imported and not used: addon`
> correct sample code

- OWNERS
atoato88 has been a great contributor, and is willing to become a reviewer
cc @atoato88
/assign johnsonj
> Add atoato88 to reviewers

- pkg/patterns/declarative/pkg/watch/dynamic.go
It's not entirely clear whether it's actually required, but it's
certainly a good defensive practice.
> Always close watchers

- .github/workflows/kind-config.yaml
- .github/workflows/main.yml
No actual testing yet, just setting up the framework.
Based on https://github.com/kind-ci/examples
> Kind e2e test using github actions

- .github/workflows/main.yml
- go.mod
This should stop go.mod / go.sum from spuriously changing when the code/tests are run.
> github actions: try running go mod tidy also

- pkg/patterns/declarative/reconciler.go
Removes duplicate fn also present in https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/pkg/patterns/addon/pkg/status/kstatus.go#L73
> Remove duplicate fn

- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
Fixes panic when enabling metrics on an operator.
> Fix metrics reconcilation

- README.md
- docs/addon/walkthrough/README.md
- docs/addon/walkthrough/tests.md
Fixes typos, broken links, grammar and capitalization.
> Various docs fixes

- pkg/patterns/declarative/reconciler.go
Running object transforms on the raw kustomize files isn't consistent
with how they are normally used, but it also is very difficult to
pre-transform kustomize inputs - for example if we remove an object,
it will likely still be referenced from kustomization.yaml
> Don't run transform twice on kustomize inputs

- pkg/test/mocks/client.go
- pkg/test/mocks/client_test.go
Although it's a fake client, we want it to behave like the real one!
> fakeClient should always return NotFound error

- pkg/patterns/declarative/watch.go
A little more compact, and probably more correct.
> Use labels helper to build label selector

- OWNERS
atoato88 has demonstrated deep understanding of the code, and has a
track record of participation.  Thank you atoato88!
> Make atoato88 an approver

- pkg/patterns/declarative/pkg/watch/dynamic.go
This avoids the race when we were (mistakenly) sharing the lastRV map.
Issue #193
> dynamic watch: scope lastRV to each watch

- .github/workflows/main.yml
- docs/addon/walkthrough/README.md
- examples/guestbook-operator/Dockerfile
- examples/guestbook-operator/go.mod
- go.mod
Bumps go 1.16 -> 1.17 and k8s.io/... deps 1.22.2 -> 1.22.3
Part of https://github.com/kubernetes-sigs/kubebuilder/issues/2421
> Bump go to 1.17

- go.mod
- go.sum
- hack/smoketest.go
This is only in test code, so low risk.
> Replace (old) dependencies on glog with klog

- CONTRIBUTING.md
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #240
> updated with latest link

- pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
> Fix code comments

- pkg/patterns/declarative/pkg/applier/exec_test.go
- pkg/test/mocks/client.go
Should be no-ops, but best to keep the tools happy.
> tests: fix some vet/linter errors

- pkg/patterns/declarative/pkg/applier/direct_test.go
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/expected.yaml
- pkg/test/httprecorder/request_log.go
Switch our golden output to a more readable style, intended to look a
bit like an HTTP traffic log.
> Tests: Format logs in HTTP style

- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/applier/direct_test.go
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/expected.yaml
- pkg/test/httprecorder/request_log.go
The discovery rest mapper is non-deterministic, which makes it hard to use with our tests.
Builds on #247
> tests: switch to controller restmapper

- pkg/mocks/mockkubeapiserver/patchresource.go
- pkg/mocks/mockkubeapiserver/postresource.go
- pkg/mocks/mockkubeapiserver/putresource.go
- pkg/patterns/declarative/pkg/applier/direct.go
Fixing up problems identified in code review (thank you!)
> Cleanup some missing comments, bad variable naming, missing error handling

- mockkubeapiserver/apiserver.go
- mockkubeapiserver/deleteresource.go
- mockkubeapiserver/listresource.go
- mockkubeapiserver/memorystorage.go
- mockkubeapiserver/memorystorage_watch.go
- mockkubeapiserver/patchresource.go
- mockkubeapiserver/postresource.go
- mockkubeapiserver/putresource.go
- pkg/patterns/declarative/metrics.go
- pkg/patterns/declarative/metrics_test.go
- pkg/patterns/declarative/pkg/applier/applylib.go
A few changes needed:
* mockkubeapiserver doesn't support patching of maps (yet), as that
depends on the OpenAPI, so we switch to ConfigMap and
Server-Side-Apply.
* the metrics test relies on watch, so we add a basic implementation
of watch to the mockkubeapiserver
> Use mockkubeapiserver in metrics_test

- pkg/patterns/addon/patch.go
- pkg/patterns/addon/pkg/loaders/fs.go
- pkg/patterns/addon/pkg/loaders/git.go
- pkg/patterns/addon/pkg/loaders/http.go
- pkg/patterns/addon/pkg/loaders/types.go
- pkg/patterns/addon/pkg/loaders/types_test.go
- pkg/patterns/addon/pkg/loaders/versions_test.go
- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/addon/pkg/status/kstatus.go
- pkg/patterns/addon/pkg/status/version.go
- pkg/patterns/declarative/image.go
- pkg/patterns/declarative/labels.go
- pkg/patterns/declarative/pkg/applier/exec.go
- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/patch.go
- pkg/patterns/declarative/pkg/manifest/patch_test.go
- pkg/patterns/declarative/pkg/watch/dynamic.go
- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/sort.go
- pkg/patterns/declarative/watch.go
- pkg/restmapper/caching.go
- pkg/restmapper/controllerrestmapper.go
Attempt to plumb the context through also, wherever we have one.
> Use logger from context.Context

- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/declarative/pkg/manifest/objects.go
> Create nil-safe wrapper around Items

- pkg/patterns/addon/pkg/status/aggregate.go
A little misleading to do otherwise!
> Report status as unhealthy if we failed to reconcile

- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/patterns/declarative/pkg/applier/testdata/applylib/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/applylib/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/applylib/simple3/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/expected.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
- pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
- pkg/test/httprecorder/http_recorder.go
- pkg/test/httprecorder/request_log.go
- testing: record http responses also
- testdata: update to include responses also
> testing: record http responses also

- pkg/patterns/declarative/options.go
- pkg/patterns/declarative/reconciler.go
This is useful in tests and probably in real-world also.
> Allow applier to be overridden per-controller

- mockkubeapiserver/Makefile
- mockkubeapiserver/apiserver.go
- mockkubeapiserver/forked/README.md
- mockkubeapiserver/forked/managedfields.go
- mockkubeapiserver/go.mod
- mockkubeapiserver/kubernetes_builtin_schema.go
- mockkubeapiserver/kubernetes_builtin_schema.yaml
- mockkubeapiserver/memorystorage.go
- mockkubeapiserver/patchresource.go
- mockkubeapiserver/schema.go
- mockkubeapiserver/schema_test.go
Add a test before starting to use the SMD library to describe the
built-in types.
> mockkubeapiserver: add test using SMD library

- pkg/test/golden/validator.go
- pkg/test/mocks/client.go
- pkg/test/mocks/manager.go
This means we need fewer code changes to support different interfaces.
> tests: embed interfaces in mocks

- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/addon/pkg/status/kstatus.go
- pkg/patterns/addon/pkg/status/version.go
- pkg/patterns/declarative/pkg/applier/direct.go
- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/pkg/manifest/objects_test.go
- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/watch.go
Cherry pick of #212 on release-0.11
#212:Introduce setters for name and namespace
Edited to remove release notes for future release and to continue to expose underlying variables (for compatability).
> Cherry pick of #212: Introduce setters for name and namespace

- reconciler-options.md
related to https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/299
cc @atoato88 @justinsb
> Add doc for without-kustomize tag

- mockkubeapiserver/direct_http.go
This is probably a little faster and avoids opening a socket.
> mockkubeapiserver: Support direct mode without listening on a socket

- mockkubeapiserver/apiserver.go
- mockkubeapiserver/controllers.go
When a user creates a CRD, register it as a recognized type.
> mockkubeapiserver: Add basic CRD handling

- pkg/patterns/declarative/pkg/applier/applylib_test.go
- pkg/test/httprecorder/http_recorder.go
- pkg/test/httprecorder/request_log.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Otherwise we were trying to buffer them entirely, which wasn't working well.
Note that we now also capture the second reconcile, triggered by the status update.
> httprecorder: recognize and stream watch responses

- pkg/patterns/addon/pkg/status/aggregate.go
- pkg/patterns/addon/pkg/status/basic.go
- pkg/patterns/addon/pkg/status/kstatus.go
- pkg/patterns/declarative/pkg/manifest/objects.go
- pkg/patterns/declarative/reconciler.go
- pkg/patterns/declarative/status.go
- pkg/patterns/declarative/statusinfo.go
- pkg/test/testreconciler/simpletest/controller.go
- pkg/test/testreconciler/simpletest/controller_test.go
- pkg/test/testreconciler/simpletest/testdata/channels/packages/simpletest/0.1.0/manifest.yaml
- pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
We pass in a function to query the current state of objects, this
allows us to cache the results (if using SSA) and allows for cluster
targeting.
> Better status functions

- applylib/go.mod
- applylib/go.sum
- dev/test
- hack/ci/test.sh
- mockkubeapiserver/controllers.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Write some simple stub-logic so that deployments immediately
have a status indicating that they are ready.
> mockkubeapiserver: deployments should become healthy

- pkg/patterns/declarative/reconciler.go
Refactor to ensure that we build and flatten the objects in one place,
simplifying execution.  The intermediate call to VersionCheck (should)
prefer flattened objects.
> Simplify List flattening logic

- pkg/restmapper/caching.go
- pkg/restmapper/controllerrestmapper.go
- pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Also ensure this access is always guarded with a mutex.
> restmapper: Ensure that we only access cached fields from a single method

- applylib/applyset/health.go
resolve [comment](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/309/files#r1170503400)
> fix: catch unknown kstatus value

- pkg/patterns/declarative/kustomize/enabled.go
- reconciler-options.md
> fix: align go build tag delimiters to hyphen

- OWNERS
This was discussed already when adding me to reviewers in #381 but hasn't happened yet.
> owners: promote tomasaschan to owner
